### ISSUE TITLE
Library ADT7410

### ISSUE THREAD

**Issue by janhendry** [madmachineio/MadDrivers#54]
I want add library for the temperature sensor ADT7410. See [here](https://github.com/janhendry/MadDrivers/tree/feature/ADT7410).

But now I have the problem with the I2C interface.
[code](https://github.com/janhendry/MadDrivers/blob/feature/ADT7410/Examples/ADT7410/ReadTemp/Sources/ReadTemp/main.swift)
```swift
import SwiftIO
import MadBoard
import ADT7410


let i2c = I2C(Id.I2C1)

while (true) {
    sleep(ms: 2000)
    var buffer: [UInt8] = []
    i2c.writeRead(0x00, into: &buffer, readCount: 1, address:  0x48)
}
```
I get this error message.

error: SwiftIO.I2C.writeRead(_:into:readCount:address:) line 373 -> Invalid argument

I can't really explain this error. Or is it solved with 0.7.0-alpha.1?

board: SwiftIOBoard
mm-sdk: 0.7.0-alpha.0
XCode: Version 13.4.1 (13F100)

**Comment by Ines333** [comment]
Hi Jan,

That's because the method `writeRead` will compare the length of `buffer`  and `readCount`, then choose the smaller one and override those elements in the `buffer`. In your case, the `buffer` count is 0, which is less than the `readCount`, therefore the actually read length will be 0 which is an invalid parameter.

Actually, you can leave the `readCount` to be nil, so the number of data to be read will directly equal the length of the `buffer`. You can check [this API explanation](https://madmachineio.github.io/SwiftIO/documentation/swiftio/i2c/writeread(_:into:readcount:address:)).

So you can change your code as below:

```swift
import SwiftIO
import MadBoard
import ADT7410

let i2c = I2C(Id.I2C1)

while (true) {
    sleep(ms: 2000)
    var buffer = [UInt8](repeating: 0, count: 1)
    i2c.writeRead(0x00, into: &buffer, address:  0x48)
}
```

**Comment by janhendry** [comment]
Okay, easier than I thought. But I would include this info in the docu.
